apiKey: "M0PR0S2VTEGG62YI8WE721Mer8Oe44IiK0lsgnlsbWsTgdpCY"
sharedSecret: "EuOqqPT#67eGnp2iz$Kn3pNfxWWveQxfN-@LDY+D"
visaUrl: "https://sandbox.api.visa.com/"
userId: "AEWZRMXQLW0H61YK5JXX21fl6YtvACeoJLIuMPmEia1xNYd3A"
password: "Nkv5qztv417Mcg6ozRvTTkR4Ts"
cert: "/Users/razahussain/Desktop/cert.pem"
key: "/Users/razahussain/Desktop/key_82f86442-3ef3-41ea-95fa-cdc7dc7c6498.pem"
vctcTestPan: "{put your pan number from test data under consumer rules api -> register a card here}"
tnsPartnerBid: "{put your tns partner bid here}"
tnsCardNumbers: '{put your visa travel notification service card account numbers here}'
vtaServiceId: "{put your vta service id here}"
vtaCustomerId: "{put your vta customer id here}"
vtaCommunityCode: "{put your vta community code here}"
vtaPortfolioNumber: "{put your portfolio number here}"
vtaCreateCustomerAddress: '{put your adress from the create customer call here}'
vtaCreateCustomerCardExpiryDate: "{put your vta create customer card expiry date here}"
vtaCreateCustomerCardNumber: "{put your vta create customer card number here}"
vtaCreateCustomerCardSecurityCode: "{put your vta create customer card security code here}"
vtaCreateCustomerLastFour: "{put your vta create customer last four here}"
vtaCreateCustomerIsActive: "{put your vta create customer isActive here}"
vtaCreateCustomerPreferedCountryCode: "{put your vta create customer prefered  country code here}"
vtaCreateCustomerPreferedCurrencyCode: "{put your vta create customer prefered  currency code here}"
vtaCreateCustomerPreferedLanguage: "{put your vta create customer prefered  language here}"
vtaCreateCustomerPreferedTimeZone: "{put your vta create customer prefered  time zone here}"
vtaReplaceCardNewAddress: '{put your vta replace card address here}'
vtaReplaceCardExpiryDate: "{put your vta replace card expiry date here}"
vtaReplaceCardSecurityCode: "{put your vta replace card security code here}"
vtaReplaceCardNumber: "{put your vta replace card number here}"
vtaReplaceCardLastFour: "{put your vta replace card last 4 digits here}"
vtaNotificationContactType: "{put your vta notification contact type here}"
vtaPreferredLanguageCode: "{put your vta notification preferred language here}"
mlcIssuerId: "{put your enrollments api issuer id here}"
mlcDeviceId: "{put your enrollments api device id here}"
mlcClientMessageID: "{put your enrollments api client message id here}"
mlcPrimaryAccountNumber: "{put your enrollments api primary account number here}"   
mlcMessageId: "{put your locations api message id here}"
checkoutCallId: "{put your visa checkout callId here}"
