# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49799f0c3ba850d10b41924ed334bffa791414d89a96d056d1e74f18236411943df2cd01a5a894b0fead1fb2d79967105efc2f10d8dfe3533c057200459a3bef

test:
  secret_key_base: 376d72c758439898d12232fc8b0772064bbe0c24b14165e2762c98dbba63f04ffcfd827d2f7046aa068bdaf044931514a47fc1054f127832d30f38d79d50ec22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
